#!/usr/bin/env python3
"""Generate the on-screen "C-Down: Warp Map" prompt texture as an IA8 C array.

N64 IA8 = 1 byte per texel: high nibble = intensity (0-15), low nibble = alpha (0-15).
We render white shapes/text (full intensity) and use the rendered alpha as coverage.
"""
import os
from PIL import Image, ImageDraw, ImageFont

W, H = 128, 16
OUT_H = os.path.join(os.path.dirname(__file__), "..", "src", "warp_prompt_tex.h")
PREVIEW = os.path.join(os.path.dirname(__file__), "prompt_preview.png")

img = Image.new("RGBA", (W, H), (0, 0, 0, 0))
d = ImageDraw.Draw(img)

def load_font(size):
    for p in [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/System/Library/Fonts/SFNS.ttf",
        "/Library/Fonts/Arial.ttf",
    ]:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                pass
    return ImageFont.load_default()

font = load_font(12)

# Draw a small "C" button glyph: a filled circle outline with "C" inside.
# Keep it readable at native res. Left side icon, then a down arrow, then text.
cx, cy, r = 7, H // 2, 6
d.ellipse([cx - r, cy - r, cx + r, cy + r], outline=(255, 255, 255, 255), width=1)
small = load_font(9)
d.text((cx, cy), "C", font=small, fill=(255, 255, 255, 255), anchor="mm")

# Down arrow (triangle) right after the C button to indicate C-Down / C-stick down.
ax = 16
d.polygon([(ax, 3), (ax + 8, 3), (ax + 4, 11)], fill=(255, 255, 255, 255))

# Label
d.text((28, H // 2), "Warp Map", font=font, fill=(255, 255, 255, 255), anchor="lm")

img.save(PREVIEW)
# Upscaled preview for eyeballing
img.resize((W * 4, H * 4), Image.NEAREST).save(PREVIEW.replace(".png", "_4x.png"))

# Convert to IA8
px = img.load()
data = bytearray()
for y in range(H):
    for x in range(W):
        rr, gg, bb, aa = px[x, y]
        inten = max(rr, gg, bb)  # white where drawn
        ia = ((inten >> 4) << 4) | (aa >> 4)
        data.append(ia)

with open(OUT_H, "w") as f:
    f.write("// Auto-generated by tools/gen_prompt_tex.py. Do not edit by hand.\n")
    f.write("// IA8 texture, %dx%d.\n" % (W, H))
    f.write("#ifndef WARP_PROMPT_TEX_H_GUARD\n#define WARP_PROMPT_TEX_H_GUARD\n\n")
    f.write("#define WARP_PROMPT_TEX_WIDTH %d\n" % W)
    f.write("#define WARP_PROMPT_TEX_HEIGHT %d\n\n" % H)
    f.write("static const unsigned char gWarpPromptTex[%d] __attribute__((aligned(8))) = {\n" % len(data))
    for i in range(0, len(data), 16):
        f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n\n#endif\n")

print("wrote", OUT_H, "(%d bytes)" % len(data))
print("preview", PREVIEW)
