#!/usr/bin/env python3
"""Generate the on-screen "C-Down: Warp Map" prompt texture as an IA8 C array.

N64 IA8 = 1 byte per texel: high nibble = intensity (0-15), low nibble = alpha (0-15).
We render white shapes/text (full intensity) and use the rendered alpha as coverage; the
mod tints the result black at draw time via the primitive color.

The texture is authored at 256x32 (4x the on-screen footprint) and rendered from a much
larger supersampled canvas, so it stays sharp when RT64 upscales it to a high internal
resolution. The mod uploads it to TMEM in 8-row strips to stay within the 4 KB tile limit.
"""
import os
from PIL import Image, ImageDraw, ImageFont

# Authored (source) texture size. Drawn on-screen at half this in each axis.
W, H = 256, 32
# Supersample factor for crisp edges; rendered big then downscaled with LANCZOS.
SS = 4
OUT_H = os.path.join(os.path.dirname(__file__), "..", "src", "warp_prompt_tex.h")
PREVIEW = os.path.join(os.path.dirname(__file__), "prompt_preview.png")


def load_font(size, bold=True):
    candidates = [
        "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
        "/System/Library/Fonts/Supplemental/Arial.ttf",
        "/Library/Fonts/Arial Bold.ttf",
        "/Library/Fonts/Arial.ttf",
        "/System/Library/Fonts/SFNS.ttf",
    ]
    if not bold:
        candidates = candidates[1:]
    for p in candidates:
        if os.path.exists(p):
            try:
                return ImageFont.truetype(p, size)
            except Exception:
                pass
    return ImageFont.load_default()


big = Image.new("RGBA", (W * SS, H * SS), (0, 0, 0, 0))
d = ImageDraw.Draw(big)


def s(v):
    return v * SS


# C-button glyph: a bold circle outline with a "C" inside.
cx, cy, r = s(15), s(H // 2), s(12)
d.ellipse([cx - r, cy - r, cx + r, cy + r], outline=(255, 255, 255, 255), width=s(2))
cfont = load_font(s(17))
d.text((cx, cy - s(1)), "C", font=cfont, fill=(255, 255, 255, 255), anchor="mm")

# Down arrow (C-stick down) immediately to the right of the button.
ax, atop, abot = s(33), s(8), s(24)
d.polygon([(ax, atop), (ax + s(14), atop), (ax + s(7), abot)], fill=(255, 255, 255, 255))

# Label.
label_font = load_font(s(22))
d.text((s(56), s(H // 2) - s(1)), "Warp Map", font=label_font, fill=(255, 255, 255, 255), anchor="lm")

# Downscale to the authored size for crisp anti-aliased edges.
img = big.resize((W, H), Image.LANCZOS)

img.save(PREVIEW)
img.resize((W * 2, H * 2), Image.NEAREST).save(PREVIEW.replace(".png", "_2x.png"))

# Convert to IA8.
px = img.load()
data = bytearray()
for y in range(H):
    for x in range(W):
        rr, gg, bb, aa = px[x, y]
        inten = max(rr, gg, bb)  # white where drawn
        ia = ((inten >> 4) << 4) | (aa >> 4)
        data.append(ia)

with open(OUT_H, "w") as f:
    f.write("// Auto-generated by tools/gen_prompt_tex.py. Do not edit by hand.\n")
    f.write("// IA8 texture, %dx%d (drawn on-screen at half size).\n" % (W, H))
    f.write("#ifndef WARP_PROMPT_TEX_H_GUARD\n#define WARP_PROMPT_TEX_H_GUARD\n\n")
    f.write("#define WARP_PROMPT_TEX_WIDTH %d\n" % W)
    f.write("#define WARP_PROMPT_TEX_HEIGHT %d\n\n" % H)
    f.write("static const unsigned char gWarpPromptTex[%d] __attribute__((aligned(8))) = {\n" % len(data))
    for i in range(0, len(data), 16):
        f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n\n#endif\n")

print("wrote", OUT_H, "(%d bytes)" % len(data))
print("preview", PREVIEW)
